"""Build docs/data_audit.json — the payload behind the dashboard's Data tab.

WHY A SEPARATE FILE, NOT INLINED. Every other dashboard dataset is injected
into template.html between the __DASHBOARD_DATA_*__ markers, which is why
docs/index.html is already ~7.3MB. This payload is ~1MB and exists purely
for inspection, so inlining it would make every page load pay for data most
visits never open. The Data tab fetches it on first click instead.

WHAT IS AND IS NOT IN HERE. The full constituent history cannot be shipped:
data/constituents_*.json totals 60-80MB (ICHN alone is 5.3MB). So the
roster section carries the COUNT per Friday across all history, plus the
actual ticker list for the most recent Friday only. Likewise the breadth
section samples the series at Fridays rather than every trading day — daily
would be 5-10MB, and Fridays are the dates the strategies actually
rebalance on, so they are the decision points a reader wants to audit.

Anything summarised here is derived at build time from the same panels the
dashboard renders, so the tab cannot drift from the dashboard: both are
regenerated by the same pipeline run.

Run:
    python scripts/build_data_audit.py            # writes docs/data_audit.json
    python scripts/build_data_audit.py --stdout   # print, do not write
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fetch_constituents as fc  # noqa: E402
from etf_registry import (  # noqa: E402
    ETF_REGISTRY,
    EUROPE_SUPERSECTORS_CANDIDATE,
    UNIVERSE_GLOBAL,
)
# One staleness policy, defined next to the incident that motivated it.
# This module reads the same gitignored prices_cache_*.parquet and reports
# each name's last observed close as its CURRENT price, so an unrefreshed
# cache publishes a days-old number under today's date here exactly as it
# does in the panels.
from build_panel_series import (  # noqa: E402
    OVERRIDE_ENV,
    StalePriceCacheError,
    check_cache_freshness,
)
from nyse_sessions import last_completed_session  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DOCS = PROJECT_ROOT / "docs"
OUT = DOCS / "data_audit.json"

# Round breadth ratios to 4dp. They are proportions in [0,1]; full float
# repr would roughly double the payload for digits nobody reads.
_ROUND = 4

# Panels this run could not report faithfully. Both are populated during
# build() and consumed by write(), which refuses to publish if either is
# non-empty — the committed file is then better than anything this run
# could produce, so overwriting it is strictly a regression.
#
#   _stale_caches  price cache too far behind to report as current.
#   _missing_raw   the iShares payload the holdings detail is parsed from
#                  is absent. It returns [] on a missing source by design
#                  ("a partial payload beats a failed build"), which is
#                  right for the page and wrong for the file: a local
#                  rebuild without data/raw_ishares/<ETF>_<date>.json
#                  quietly replaced 3,370 populated holdings rows across
#                  all 38 panels with empty lists, and the result is a
#                  well-formed file that simply asserts less.
_stale_caches: list[str] = []
_missing_raw: list[str] = []
_expected_session: object = None      # memoised; the lookup hits a calendar


def _expected() -> "object | None":
    """Last completed NYSE session, or None when the guard is overridden."""
    global _expected_session
    import os
    if os.environ.get(OVERRIDE_ENV):
        return None
    if _expected_session is None:
        _expected_session = last_completed_session(
            datetime.now(timezone.utc))
    return _expected_session


def _round(v):
    return None if v is None else round(float(v), _ROUND)


def _role(etf: str) -> str:
    """How this panel relates to the deployed book — the first thing a
    reader needs, because the 14 Europe supersectors are captured for
    research and are NOT traded."""
    if etf in UNIVERSE_GLOBAL:
        return "deployed"
    if etf in EUROPE_SUPERSECTORS_CANDIDATE:
        return "candidate"
    return "registered"


def _reference_date(b: dict) -> str | None:
    """Last session whose breadth was computed on a full roster.

    A panel's final bar can be built from a handful of names when the
    price vendor has not published every close yet — on 2026-08-07 the
    European panels had n_with_ma50 = 2. Such a bar is not a breadth
    reading, so the constituent table anchors to the last bar where at
    least 90% of the roster had a usable moving average."""
    ser = (b or {}).get("series") or {}
    dates, nc, nm = ser.get("dates"), ser.get("n_constituents"), ser.get("n_with_ma50")
    if not dates or not nc or not nm:
        return None
    for i in range(len(dates) - 1, -1, -1):
        if nc[i] and nm[i] is not None and nm[i] >= 0.9 * nc[i]:
            return dates[i]
    return None


def _latest_holdings_detail(etf: str, actual_date: str | None,
                              ref_date: str | None = None) -> list[dict]:
    """Per-constituent weight, name, sector and 50-day MA state.

    Two sources, both already on disk after a refresh — no network:

      - data/raw_ishares/<ETF>_<YYYYMMDD>.json: the API payload the roster
        was parsed from. It carries holdingPercent, issueName and sectorName,
        none of which survive into constituents_*.json (that file keeps only
        the resolved ticker list).
      - data/prices_cache_<etf>.parquet: daily closes, from which the
        50-day moving average is recomputed (compute_breadth.MA_PERIOD).

    The MA state is the point. The panel's ma_breadth IS the share of
    constituents above their 50-day MA, so listing which names are above and which are below
    turns the headline number from an assertion into something a reader can
    add up. `above` is None where the name has no usable price history —
    those are dropped from BOTH numerator and denominator upstream, which is
    why breadth tilts toward survivors.

    Tickers are resolved through the same _resolve_yf_symbol path the roster
    used, so weights key to the same symbols the price cache holds. Returns
    [] rather than raising when either source is missing: this is an
    inspection payload, and a partial one beats a failed dashboard build.
    """
    if not actual_date:
        return []
    cfg = ETF_REGISTRY.get(etf) or {}
    raw = DATA_DIR / "raw_ishares" / f"{etf}_{actual_date.replace('-', '')}.json"
    if not raw.exists():
        if etf not in _missing_raw:
            _missing_raw.append(etf)
        return []
    try:
        payload = json.loads(raw.read_text(encoding="utf-8"))
        if payload.get("_no_holdings"):
            return []
        dps = fc._holdings_datapoints(payload)
    except Exception:
        return []

    def col(k):
        return (dps.get(k) or {}).get("value")

    tick, acl = col("ticker"), col("assetClass")
    if not tick or not acl:
        return []
    wt, nm, sec = col("holdingPercent"), col("issueName"), col("sectorName")
    exch, loc = col("exchange"), col("countryOfRisk")
    overrides = cfg.get("ticker_overrides", {})
    suffix = cfg.get("apply_exchange_suffix", False)

    # Moving-average state per symbol, from the local price cache.
    #
    # TWO THINGS HERE ARE EASY TO GET WRONG, AND I GOT BOTH WRONG FIRST TIME.
    #
    # 1. The window is compute_breadth.MA_PERIOD (50), NOT 200. The panel's
    #    ma_breadth is the share above the 50-day MA. Strategy A's SELECTION
    #    ranks on a 200-day breadth computed elsewhere — a different measure.
    #    Importing MA_PERIOD rather than hardcoding keeps this reconciled if
    #    the window ever changes.
    # 2. The average must be taken per ticker on its OWN traded sessions via
    #    per_ticker_apply, never with a plain rolling() over the union date
    #    grid. On the union grid a European name is NaN on every US-only
    #    session, and min_periods then voids the window — the documented bug
    #    that once erased ~40% of European ma_breadth coverage.
    ma_state: dict[str, tuple] = {}
    pq = DATA_DIR / f"prices_cache_{etf.lower()}.parquet"
    if pq.exists():
        try:
            import pandas as pd
            import compute_breadth as cb
            px = pd.read_parquet(pq)
            # Record, then let it fall through to the handler below, which
            # zeroes ma_state. Reporting these names as having NO price is
            # the honest degradation; reporting a three-day-old close as
            # current is the failure being guarded.
            try:
                check_cache_freshness(etf, px.index.max().date(), _expected())
            except StalePriceCacheError:
                if etf not in _stale_caches:
                    _stale_caches.append(etf)
                raise
            ma = cb.per_ticker_apply(
                px, lambda s: s.rolling(cb.MA_PERIOD,
                                         min_periods=cb.MA_PERIOD).mean())
            # Take each ticker's LAST OBSERVED value, not the frame's last
            # row. The frame is a union date grid, so on any session a
            # market did not trade — or that its vendor has not published
            # yet — that ticker's cell is NaN. For the European panels the
            # final row was NaN for every name, which read as "no price"
            # for all 57 of EXV1 rather than "not published yet".
            #
            # Forward-fill is capped at 5 sessions, matching the cap in
            # alignment.py: a short vendor gap is bridged, but a delisted
            # name is left NaN and correctly reported as having no price
            # rather than frozen at its last trade forever.
            # Anchor to the last WELL-COVERED session, not simply the last.
            # On 2026-08-07 every European panel had n_with_ma50 = 2 out of
            # 26-32: the vendor had not published Friday European closes, so
            # that bar's ma_breadth was computed on two names and printed
            # 0.0 / 0.5 / 1.0. Anchoring there would make this table
            # disagree with a number that is itself meaningless.
            if ref_date is not None:
                px = px.loc[:ref_date]
                ma = ma.loc[:ref_date]
            last_px = px.ffill(limit=5).iloc[-1]
            last_ma = ma.ffill(limit=5).iloc[-1]
            for sym in px.columns:
                p, m = last_px.get(sym), last_ma.get(sym)
                if p is None or m is None or pd.isna(p) or pd.isna(m):
                    continue
                ma_state[sym] = (float(p), float(m))
        except Exception:
            ma_state = {}

    out: list[dict] = []
    seen: set[str] = set()
    for i in range(len(tick)):
        if (acl[i] or "").strip() != "Equity":
            continue
        rawt = str(tick[i] or "").strip()
        if rawt in {"", "-"}:
            continue
        if suffix:
            sym = fc._resolve_yf_symbol(
                rawt, (exch[i] or "").strip() or None if exch else None,
                overrides,
                location=(loc[i] or "").strip() or None if loc else None)
        else:
            sym = overrides.get(rawt, rawt.replace(".", "-"))
        if not sym or sym in seen:
            continue
        seen.add(sym)
        price, mavg = ma_state.get(sym, (None, None))
        out.append({
            "sym": sym,
            "name": (nm[i] if nm else None),
            "sector": (sec[i] if sec else None),
            "w": round(float(wt[i]), 3) if wt and wt[i] is not None else None,
            # None = no usable price history, NOT "below".
            "above": None if price is None else bool(price >= mavg),
            # Distance from the 50d MA, in per cent.
            "d": None if price is None else round(100 * (price / mavg - 1), 1),
        })
    out.sort(key=lambda r: (r["w"] is None, -(r["w"] or 0)))
    return out


def _long_names() -> dict:
    """Official fund names, keyed by panel id. data/etf_names.json is the
    scanner's existing name store; the Phase 27 panels were backfilled into
    it from the product-data API's fundHeader component, which is the
    issuer's own wording rather than a vendor's guess."""
    p = DATA_DIR / "etf_names.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def build() -> dict:
    _stale_caches.clear()
    _missing_raw.clear()
    long_names = _long_names()
    summary: list[dict] = []
    roster: dict[str, dict] = {}
    breadth: dict[str, dict] = {}
    current: dict[str, dict] = {}

    for cp in sorted(DATA_DIR.glob("constituents_*.json")):
        etf = cp.stem.replace("constituents_", "").upper()
        c = json.loads(cp.read_text(encoding="utf-8"))
        snaps = c.get("snapshots", {})
        if not snaps:
            continue
        fridays = sorted(snaps)

        # --- roster history: counts + walkback provenance per Friday ---
        actual = [snaps[k].get("actual_date") for k in fridays]
        roster[etf] = {
            "friday": fridays,
            "actual": actual,
            "n": [snaps[k].get("n_tickers") for k in fridays],
            # 1 where the roster came from an earlier day than the target
            # Friday (holiday, or the refresh outran publication).
            "walkback": [
                1 if a and a != f else 0 for f, a in zip(fridays, actual)
            ],
            # 1 where the snapshot is a carried-forward copy of a prior one.
            "carried": [
                1 if "carried_forward_from" in snaps[k] else 0
                for k in fridays
            ],
        }

        # Breadth panel is loaded FIRST: the constituent table anchors to
        # its last well-covered session, so the reference date has to exist
        # before the holdings detail is built.
        bp = DATA_DIR / f"breadth_{etf.lower()}.json"
        b = json.loads(bp.read_text(encoding="utf-8")) if bp.exists() else {}
        ref = _reference_date(b)

        latest = fridays[-1]
        current[etf] = {
            "friday": latest,
            "actual": snaps[latest].get("actual_date"),
            "tickers": snaps[latest].get("tickers", []),
            "holdings": _latest_holdings_detail(
                etf, snaps[latest].get("actual_date"), ref),
            "as_of": ref,
        }

        ser = b.get("series") or {}
        dq = b.get("data_quality") or {}
        if ser.get("dates"):
            want = set(fridays)
            idx = [i for i, d in enumerate(ser["dates"]) if d in want]

            def col(name, rnd=False):
                arr = ser.get(name)
                if not arr:
                    return None
                return [(_round(arr[i]) if rnd else arr[i]) for i in idx]

            breadth[etf] = {
                "date": [ser["dates"][i] for i in idx],
                "n_constituents": col("n_constituents"),
                "n_with_price": col("n_with_price"),
                "ma": col("ma_breadth", True),
                "rsi": col("rsi_breadth", True),
                "highs": col("highs_breadth", True),
            }

        st = c.get("staleness") or {}
        health = c.get("endpoint_health") or {}
        summary.append({
            "etf": etf,
            "role": _role(etf),
            # The issuer's own fund name, e.g. "iShares STOXX Europe 600
            # Banks UCITS ETF (DE)". `proxy` is the ticker actually traded,
            # which differs from the panel id for the Europe sleeve.
            "long_name": long_names.get(etf),
            "name": (ETF_REGISTRY.get(etf) or {}).get("yfinance_trading_proxy"),
            "end_friday": c.get("end_friday"),
            "n_snapshots": len(snaps),
            "n_walkbacks": len(c.get("walkbacks") or []),
            "n_carry_forwards": len(c.get("carry_forwards") or []),
            "n_endpoint_unavailable": len(c.get("endpoint_unavailable") or []),
            "stale_days": st.get("days_since_last_real_fetch"),
            "stale_status": st.get("status"),
            "endpoint_health": health.get("status"),
            "breadth_end": b.get("end_date"),
            "n_trading_days": b.get("n_trading_days"),
            "universe_size": dq.get("universe_size"),
            "no_yf_data": dq.get("tickers_with_no_yf_data"),
            "latest_n": snaps[latest].get("n_tickers"),
            "fetched_at_utc": c.get("fetched_at_utc"),
        })

    return {
        "built_at_utc": datetime.now(timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"),
        "note": (
            "Roster history carries constituent COUNTS for every Friday plus "
            "the ticker list for the most recent Friday only — the full "
            "history is 60-80MB. Breadth is sampled at Fridays, the dates "
            "the strategies rebalance on, not every trading day."
        ),
        "summary": summary,
        "roster": roster,
        "breadth": breadth,
        "current": current,
    }


def write() -> Path:
    """Build and write docs/data_audit.json. Importable entry point —
    pipeline.py calls THIS, not main(), because main() parses sys.argv and
    would otherwise consume the caller's arguments."""
    import os

    payload = build()
    if not os.environ.get(OVERRIDE_ENV):
        reasons = []
        if _stale_caches:
            reasons.append(
                f"{len(_stale_caches)} panel(s) have a price cache behind "
                f"the last completed session ({', '.join(_stale_caches)})")
        if _missing_raw:
            reasons.append(
                f"{len(_missing_raw)} panel(s) have no local iShares "
                f"payload, so their holdings detail would be written empty "
                f"({', '.join(_missing_raw)})")
        if reasons:
            raise StalePriceCacheError(
                "data_audit NOT written — " + "; ".join(reasons) + ". The "
                "committed file was left untouched. Fix: refresh the sources "
                "(`python scripts/refresh_all.py`) and rebuild; or set "
                f"{OVERRIDE_ENV}=1 for a one-off local rebuild that accepts "
                "a thinner file.",
                list(_stale_caches) + list(_missing_raw),
            )
    text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    DOCS.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    try:
        where = OUT.relative_to(PROJECT_ROOT)
    except ValueError:
        where = OUT              # OUT redirected outside the repo (tests)
    print(f"Wrote {where} "
          f"({len(text):,} bytes, {len(text)/1024:.0f} KB) — "
          f"{len(payload['summary'])} panels")
    return OUT


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--stdout", action="store_true",
                    help="Print the payload instead of writing it.")
    args = p.parse_args()

    if args.stdout:
        print(json.dumps(build(), ensure_ascii=False, separators=(",", ":")))
        return 0
    write()
    return 0


if __name__ == "__main__":
    sys.exit(main())
